# Generated by Django 4.2.4 on 2023-08-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
