# Generated by Django 4.2.4 on 2023-08-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0002_profile_ordermodel_name_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
