# Generated by Django 4.2.4 on 2023-08-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0006_category_delete_namakantin_alter_menuitem_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='NamaKantin',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='NamaKantin',
        ),
    ]
