# Generated by Django 4.2.4 on 2023-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0007_rename_category_namakantin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namakantin',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='kantin_images/'),
            preserve_default=False,
        ),
    ]
