# Generated by Django 4.2.4 on 2023-08-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0009_alter_namakantin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='jumlah',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='NamaKantin',
            field=models.ManyToManyField(to='makanan.namakantin'),
        ),
    ]
