# Generated by Django 4.2.4 on 2023-08-06 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('NIM', models.CharField(max_length=20)),
                ('jurusan', models.TextField(choices=[('1', 'Teknik Informatika'), ('2', 'Sistem dan Teknologi Informasi'), ('3', 'Teknik Elektro'), ('4', 'Teknik Tenaga Listrik'), ('4', 'Teknik Telekomunikasi'), ('4', 'Teknik Biomedis'), ('5', 'Matematika'), ('6', 'Aktuaria'), ('7', 'Fisika'), ('8', 'Astronomi'), ('9', 'Kimia'), ('10', 'Biologi'), ('11', 'Mikrobiologi'), ('12', 'Rekayasa Hayati'), ('13', 'Rekayasa Pertanian'), ('14', 'Rekayasa Kehutanan'), ('15', 'Teknologi Pasca Panen'), ('16', 'Sains dan Teknologi Farmasi'), ('17', 'Farmasi Klinik dan Komunitas'), ('18', 'Teknik Geologi'), ('19', 'Teknik Geodesi dan Geomatika'), ('20', 'Meteorologi'), ('21', 'Oseanografi'), ('22', 'Teknik Pertambangan'), ('23', 'Teknik Perminyakan'), ('24', 'Teknik Geofisika'), ('25', 'Teknik Metalurgi'), ('26', 'Teknik Kimia'), ('27', 'Teknik Fisika'), ('28', 'Teknik Industri'), ('29', 'Manajemen Rekayasa'), ('30', 'Teknik Pangan'), ('31', 'Teknik Bioenergi dan Kemurgi'), ('32', 'Teknik Mesin'), ('33', 'Teknik Dirgantara'), ('34', 'Teknik Material'), ('35', 'Teknik Sipil'), ('36', 'Teknik Lingkungan'), ('37', 'Teknik Kelautan'), ('38', 'Teknik dan Pengelolaan Sumber Daya Air'), ('39', 'Rekayasa Infrastruktur Lingkungan'), ('40', 'Arsitektur'), ('41', 'Perencanaan Wilayah dan Kota'), ('42', 'Manajemen'), ('43', 'Kewirausahaan'), ('44', 'Seni Rupa'), ('45', 'Kriya'), ('46', 'Desain Interior'), ('47', 'Desain Komunikasi Visual'), ('48', 'Desain Produk')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
